[31mCMake Error at /opt/ros/humble/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:59 (message):
  execute_process(/home/linuxbrew/.linuxbrew/bin/python3 -m rosidl_adapter
  --package-name livox_interfaces --arguments-file
  /home/spaaaaace/Code/mid70/2025_radar_station/build/livox_interfaces/rosidl_adapter__arguments__livox_interfaces.json
  --output-dir
  /home/spaaaaace/Code/mid70/2025_radar_station/build/livox_interfaces/rosidl_adapter/livox_interfaces
  --output-file
  /home/spaaaaace/Code/mid70/2025_radar_station/build/livox_interfaces/rosidl_adapter/livox_interfaces.idls)
  returned error code 1:

  Traceback (most recent call last):

    File "<frozen runpy>", line 198, in _run_module_as_main
    File "<frozen runpy>", line 88, in _run_code
    File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__main__.py", line 19, in <module>
      sys.exit(main())
               ~~~~^^
    File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/main.py", line 53, in main
      abs_idl_file = convert_to_idl(
          pathlib.Path(basepath), args.package_name,
          pathlib.Path(relative_path), output_dir)
    File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__init__.py", line 18, in convert_to_idl
      from rosidl_adapter.msg import convert_msg_to_idl
    File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/msg/__init__.py", line 16, in <module>
      from rosidl_adapter.resource import expand_template
    File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/resource/__init__.py", line 19, in <module>
      import em

  ModuleNotFoundError: No module named 'em'

Call Stack (most recent call first):
  /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
  CMakeLists.txt:24 (rosidl_generate_interfaces)

[0m
